import './globals.css';

export const metadata = {
  title: 'Anime Saying...',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-300 dark:bg-slate-900 h-screen w-screen font-lato">{children}</body>
    </html>
  );
}
